// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP267hJD24dWZ8xHQK4PWRRwKa9Fndb04',
    appId: '1:877661901506:web:2a98db1809dbe39ff1215b',
    messagingSenderId: '877661901506',
    projectId: 'student-management-4f2e5',
    authDomain: 'student-management-4f2e5.firebaseapp.com',
    storageBucket: 'student-management-4f2e5.appspot.com',
    measurementId: 'G-EW13E1NEK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYxNqs_Xtp4iSXoBsTtGooJcjUhLLPzs4',
    appId: '1:877661901506:android:337a2e556355c6e5f1215b',
    messagingSenderId: '877661901506',
    projectId: 'student-management-4f2e5',
    storageBucket: 'student-management-4f2e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBCwmkP3JKDAp0klE-jTtEBf-qhlCAIL8',
    appId: '1:877661901506:ios:5453708d2b777ba1f1215b',
    messagingSenderId: '877661901506',
    projectId: 'student-management-4f2e5',
    storageBucket: 'student-management-4f2e5.appspot.com',
    androidClientId: '877661901506-606saj0s2rm4stm3gj6vfvl52s0s9d36.apps.googleusercontent.com',
    iosClientId: '877661901506-695jb5ekk230qc5taghlfp3kmhbmr0v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentDetails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBCwmkP3JKDAp0klE-jTtEBf-qhlCAIL8',
    appId: '1:877661901506:ios:e27387e4dd3dffc3f1215b',
    messagingSenderId: '877661901506',
    projectId: 'student-management-4f2e5',
    storageBucket: 'student-management-4f2e5.appspot.com',
    androidClientId: '877661901506-606saj0s2rm4stm3gj6vfvl52s0s9d36.apps.googleusercontent.com',
    iosClientId: '877661901506-vri8mle6sqpipjebnrf3vemuffp67qn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentDetails.RunnerTests',
  );
}
